_group = {
  {
    group_size = 3,
    pattern = "LLL",
    opcodes = "MOVSD,MOV,MOV,",
    offsets = "8,0,16,",
    addresses = "0x8670,0x8675,0x8686,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 20,
    accessed_memory_nooverlap = 20,
    accessed_memory_overlap = 0,
    span = 24,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 1,
    pattern = "L",
    opcodes = "MOV,",
    offsets = "-1432,",
    addresses = "0x867a,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 8,
    accessed_memory_nooverlap = 8,
    accessed_memory_overlap = 0,
    span = 8,
    head = 0,
    unroll_factor = 1,
  },
}
