_group = {
  {
    group_size = 3,
    pattern = "LLL",
    opcodes = "MOV,MOVSD,MOV,",
    offsets = "0,8,16,",
    addresses = "0x86e0,0x86ec,0x86fe,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 20,
    accessed_memory_nooverlap = 20,
    accessed_memory_overlap = 0,
    span = 24,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 2,
    pattern = "LL",
    opcodes = "MOV,DIVSD,",
    offsets = "-1432,-1312,",
    addresses = "0x86e2,0x86f1,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 16,
    accessed_memory_nooverlap = 16,
    accessed_memory_overlap = 0,
    span = 128,
    head = 0,
    unroll_factor = 1,
  },
}
