_group = {
  {
    group_size = 2,
    pattern = "LS",
    opcodes = "MOVSD,MOVSD,",
    offsets = "8,8,",
    addresses = "0xdc8a,0xdc97,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 16,
    accessed_memory_nooverlap = 8,
    accessed_memory_overlap = 8,
    span = 8,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 4,
    pattern = "LLLL",
    opcodes = "MOV,MOV,MOV,MOV,",
    offsets = "0,8,16,24,",
    addresses = "0xdc09,0xdc0c,0xdc18,0xdc1c,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 32,
    accessed_memory_nooverlap = 32,
    accessed_memory_overlap = 0,
    span = 32,
    head = 0,
    unroll_factor = 4,
  },
  {
    group_size = 2,
    pattern = "LS",
    opcodes = "MOVSD,MOVSD,",
    offsets = "8,8,",
    addresses = "0xdc42,0xdc4d,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 16,
    accessed_memory_nooverlap = 8,
    accessed_memory_overlap = 8,
    span = 8,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 2,
    pattern = "LS",
    opcodes = "MOVSD,MOVSD,",
    offsets = "8,8,",
    addresses = "0xdc20,0xdc2b,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 16,
    accessed_memory_nooverlap = 8,
    accessed_memory_overlap = 8,
    span = 8,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 2,
    pattern = "LS",
    opcodes = "MOVSD,MOVSD,",
    offsets = "8,8,",
    addresses = "0xdc53,0xdc5e,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 16,
    accessed_memory_nooverlap = 8,
    accessed_memory_overlap = 8,
    span = 8,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 2,
    pattern = "LS",
    opcodes = "MOVSD,MOVSD,",
    offsets = "8,8,",
    addresses = "0xdc31,0xdc3c,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 16,
    accessed_memory_nooverlap = 8,
    accessed_memory_overlap = 8,
    span = 8,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 4,
    pattern = "LLLL",
    opcodes = "ADDSD,ADDSD,SUBSD,SUBSD,",
    offsets = "0,0,0,0,",
    addresses = "0xdc26,0xdc37,0xdc48,0xdc59,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 32,
    accessed_memory_nooverlap = 8,
    accessed_memory_overlap = 24,
    span = 8,
    head = 0,
    unroll_factor = 2,
  },
  {
    group_size = 2,
    pattern = "LS",
    opcodes = "MOVSD,MOVSD,",
    offsets = "8,8,",
    addresses = "0xdc9c,0xdca5,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 16,
    accessed_memory_nooverlap = 8,
    accessed_memory_overlap = 8,
    span = 8,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 2,
    pattern = "LS",
    opcodes = "MOVSD,MOVSD,",
    offsets = "8,8,",
    addresses = "0xdc7c,0xdc85,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 16,
    accessed_memory_nooverlap = 8,
    accessed_memory_overlap = 8,
    span = 8,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 2,
    pattern = "LS",
    opcodes = "MOVSD,MOVSD,",
    offsets = "8,8,",
    addresses = "0xdcaa,0xdcb4,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 16,
    accessed_memory_nooverlap = 8,
    accessed_memory_overlap = 8,
    span = 8,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 4,
    pattern = "LLLL",
    opcodes = "MOV,MOV,MOV,MOV,",
    offsets = "0,8,16,24,",
    addresses = "0xdc69,0xdc6c,0xdc74,0xdc78,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 32,
    accessed_memory_nooverlap = 32,
    accessed_memory_overlap = 0,
    span = 32,
    head = 0,
    unroll_factor = 4,
  },
  {
    group_size = 4,
    pattern = "LLLL",
    opcodes = "ADDSD,ADDSD,SUBSD,SUBSD,",
    offsets = "0,0,0,0,",
    addresses = "0xdc81,0xdc8f,0xdca1,0xdcb0,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 32,
    accessed_memory_nooverlap = 8,
    accessed_memory_overlap = 24,
    span = 8,
    head = 0,
    unroll_factor = 2,
  },
}
