_group = {
  {
    group_size = 8,
    pattern = "SSSSSSSS",
    opcodes = "MOVSD,MOVSD,MOVSD,MOVSD,MOVSD,MOVSD,MOVSD,MOVSD,",
    offsets = "464,464,464,464,464,464,464,464,",
    addresses = "0xfc45,0xfc5e,0xfc74,0xfc8a,0xfca0,0xfcb6,0xfccc,0xfce2,",
    stride_status = "Not Analyzed",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 64,
    accessed_memory_nooverlap = 8,
    accessed_memory_overlap = 56,
    span = 8,
    head = 0,
    unroll_factor = 8,
  },
  {
    group_size = 1,
    pattern = "L",
    opcodes = "MOVSD,",
    offsets = "0,",
    addresses = "0xfc32,",
    stride_status = "Success",
    stride = 64,
    memory_status = "Success",
    accessed_memory = 8,
    accessed_memory_nooverlap = 8,
    accessed_memory_overlap = 0,
    span = 8,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 7,
    pattern = "LLLLLLL",
    opcodes = "MOVSD,MOVSD,MOVSD,MOVSD,MOVSD,MOVSD,MOVSD,",
    offsets = "-56,-48,-40,-32,-24,-16,-8,",
    addresses = "0xfc4e,0xfc67,0xfc7d,0xfc93,0xfca9,0xfcbf,0xfcd5,",
    stride_status = "Success",
    stride = 64,
    memory_status = "Success",
    accessed_memory = 56,
    accessed_memory_nooverlap = 56,
    accessed_memory_overlap = 0,
    span = 56,
    head = 0,
    unroll_factor = 7,
  },
}
