_group = {
  {
    group_size = 3,
    pattern = "LLL",
    opcodes = "MOVUPD,MOVUPD,MOVUPD,",
    offsets = "-48,-32,-16,",
    addresses = "0x1184a,0x11860,0x1186e,",
    stride_status = "Success",
    stride = 64,
    memory_status = "Success",
    accessed_memory = 48,
    accessed_memory_nooverlap = 48,
    accessed_memory_overlap = 0,
    span = 48,
    head = 0,
    unroll_factor = 3,
  },
  {
    group_size = 1,
    pattern = "L",
    opcodes = "MOVUPD,",
    offsets = "0,",
    addresses = "0x11834,",
    stride_status = "Success",
    stride = -64,
    memory_status = "Success",
    accessed_memory = 16,
    accessed_memory_nooverlap = 16,
    accessed_memory_overlap = 0,
    span = 16,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 3,
    pattern = "LLL",
    opcodes = "MOVUPD,MOVUPD,MOVUPD,",
    offsets = "48,32,16,",
    addresses = "0x11845,0x1185a,0x1189e,",
    stride_status = "Success",
    stride = -64,
    memory_status = "Success",
    accessed_memory = 48,
    accessed_memory_nooverlap = 48,
    accessed_memory_overlap = 0,
    span = 48,
    head = 0,
    unroll_factor = 3,
  },
  {
    group_size = 1,
    pattern = "L",
    opcodes = "MOVUPD,",
    offsets = "0,",
    addresses = "0x11839,",
    stride_status = "Success",
    stride = 64,
    memory_status = "Success",
    accessed_memory = 16,
    accessed_memory_nooverlap = 16,
    accessed_memory_overlap = 0,
    span = 16,
    head = 0,
    unroll_factor = 1,
  },
}
