_group = {
  {
    group_size = 19,
    pattern = "LLLSSLLLLLLLLLSLSLL",
    opcodes = "MOV,MOV,MOV,MOV,MOVAPS,MOV,CMP,MOV,MOV,SUB,MOV,MOV,MOV,MOV,MOV,MOV,MOV,CMP,CMP,",
    offsets = "72,16,208,480,464,248,256,16,472,464,464,248,472,464,24,24,248,0,0,",
    addresses = "0xf998,0xf99d,0xf9a8,0xf9d4,0xf9e0,0xf9ed,0xf9f5,0x1164f,0xfa03,0xfa0b,0x1165f,0xfa55,0xfa76,0xfa7e,0xfa91,0xfaa4,0xfab8,0x115cc,0xfad9,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 152,
    accessed_memory_nooverlap = 76,
    accessed_memory_overlap = 76,
    span = 488,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 5,
    pattern = "SSSSS",
    opcodes = "MOV,MOVUPS,MOV,MOVUPS,MOV,",
    offsets = "16,0,16,0,8,",
    addresses = "0xfa17,0xfa23,0xfa6c,0xfa71,0xfab3,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 56,
    accessed_memory_nooverlap = 24,
    accessed_memory_overlap = 32,
    span = 24,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 2,
    pattern = "LS",
    opcodes = "MOVSD,MOVSD,",
    offsets = "0,0,",
    addresses = "0xf9be,0xf9d0,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 16,
    accessed_memory_nooverlap = 8,
    accessed_memory_overlap = 8,
    span = 8,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 1,
    pattern = "L",
    opcodes = "SUBSD,",
    offsets = "0,",
    addresses = "0xf9c2,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 8,
    accessed_memory_nooverlap = 8,
    accessed_memory_overlap = 0,
    span = 8,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 1,
    pattern = "L",
    opcodes = "XORPD,",
    offsets = "44832,",
    addresses = "0xf9c8,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 16,
    accessed_memory_nooverlap = 16,
    accessed_memory_overlap = 0,
    span = 16,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 1,
    pattern = "L",
    opcodes = "MOV,",
    offsets = "0,",
    addresses = "0xf9b8,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 8,
    accessed_memory_nooverlap = 8,
    accessed_memory_overlap = 0,
    span = 8,
    head = 0,
    unroll_factor = 1,
  },
}
