_group = {
  {
    group_size = 17,
    pattern = "LLLLLLLLLLLLLLLLL",
    opcodes = "MOV,MOV,ADD,MOV,MOV,MOV,ADD,MOV,MOV,MOV,ADD,MOV,MOV,MOV,ADD,MOV,CMP,",
    offsets = "432,472,240,24,432,472,240,24,432,472,240,24,432,472,240,24,0,",
    addresses = "0x10df6,0x10dfe,0x10e0a,0x10e33,0x10cfd,0x10d05,0x10d19,0x1168a,0x10d4c,0x10d54,0x10d64,0x1167b,0x10d9a,0x10da2,0x10db5,0x1166c,0x10df0,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 132,
    accessed_memory_nooverlap = 36,
    accessed_memory_overlap = 96,
    span = 480,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 4,
    pattern = "LSLS",
    opcodes = "MOVSD,MOVSD,MOVSD,MOVSD,",
    offsets = "0,0,0,0,",
    addresses = "0x10d73,0x10d7e,0x10dbd,0x10dcc,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 32,
    accessed_memory_nooverlap = 8,
    accessed_memory_overlap = 24,
    span = 8,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 1,
    pattern = "S",
    opcodes = "MOVSD,",
    offsets = "0,",
    addresses = "0x10ddb,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 8,
    accessed_memory_nooverlap = 8,
    accessed_memory_overlap = 0,
    span = 8,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 1,
    pattern = "S",
    opcodes = "MOVSD,",
    offsets = "0,",
    addresses = "0x10cf0,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 8,
    accessed_memory_nooverlap = 8,
    accessed_memory_overlap = 0,
    span = 8,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 1,
    pattern = "S",
    opcodes = "MOVSD,",
    offsets = "0,",
    addresses = "0x10d8d,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 8,
    accessed_memory_nooverlap = 8,
    accessed_memory_overlap = 0,
    span = 8,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 3,
    pattern = "LLS",
    opcodes = "MOV,CMP,MOV,",
    offsets = "8,16,8,",
    addresses = "0x10e15,0x10e29,0x10cf9,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 24,
    accessed_memory_nooverlap = 16,
    accessed_memory_overlap = 8,
    span = 16,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 2,
    pattern = "LS",
    opcodes = "MOVSD,MOVSD,",
    offsets = "0,0,",
    addresses = "0x10e19,0x10e24,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 16,
    accessed_memory_nooverlap = 8,
    accessed_memory_overlap = 8,
    span = 8,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 3,
    pattern = "LLS",
    opcodes = "MOV,CMP,MOV,",
    offsets = "8,16,8,",
    addresses = "0x10d6f,0x10d83,0x10d96,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 24,
    accessed_memory_nooverlap = 16,
    accessed_memory_overlap = 8,
    span = 16,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 2,
    pattern = "LS",
    opcodes = "MOVSD,MOVSD,",
    offsets = "0,0,",
    addresses = "0x10d28,0x10d32,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 16,
    accessed_memory_nooverlap = 8,
    accessed_memory_overlap = 8,
    span = 8,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 1,
    pattern = "S",
    opcodes = "MOVSD,",
    offsets = "0,",
    addresses = "0x10d40,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 8,
    accessed_memory_nooverlap = 8,
    accessed_memory_overlap = 0,
    span = 8,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 4,
    pattern = "LLLL",
    opcodes = "DIVSD,DIVSD,DIVSD,DIVSD,",
    offsets = "-8,-8,-8,-8,",
    addresses = "0x10e1e,0x10d2c,0x10d78,0x10dc2,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 32,
    accessed_memory_nooverlap = 8,
    accessed_memory_overlap = 24,
    span = 8,
    head = 0,
    unroll_factor = 4,
  },
  {
    group_size = 3,
    pattern = "LLS",
    opcodes = "MOV,CMP,MOV,",
    offsets = "8,16,8,",
    addresses = "0x10d24,0x10d36,0x10d48,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 24,
    accessed_memory_nooverlap = 16,
    accessed_memory_overlap = 8,
    span = 16,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 3,
    pattern = "LLS",
    opcodes = "MOV,CMP,MOV,",
    offsets = "8,16,8,",
    addresses = "0x10dc8,0x10dd1,0x10de4,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 24,
    accessed_memory_nooverlap = 16,
    accessed_memory_overlap = 8,
    span = 16,
    head = 0,
    unroll_factor = 1,
  },
}
