_group = {
  {
    group_size = 2,
    pattern = "LL",
    opcodes = "MOV,MOV,",
    offsets = "16,0,",
    addresses = "0xee44,0xee71,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 12,
    accessed_memory_nooverlap = 12,
    accessed_memory_overlap = 0,
    span = 20,
    head = 0,
    unroll_factor = 2,
  },
  {
    group_size = 2,
    pattern = "LL",
    opcodes = "MOV,MOV,",
    offsets = "16,0,",
    addresses = "0xee7d,0xeeaa,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 12,
    accessed_memory_nooverlap = 12,
    accessed_memory_overlap = 0,
    span = 20,
    head = 0,
    unroll_factor = 2,
  },
  {
    group_size = 4,
    pattern = "LLLL",
    opcodes = "MOV,MOV,MOV,MOV,",
    offsets = "0,0,0,0,",
    addresses = "0xedd4,0xee10,0xee48,0xee81,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 32,
    accessed_memory_nooverlap = 8,
    accessed_memory_overlap = 24,
    span = 8,
    head = 0,
    unroll_factor = 4,
  },
  {
    group_size = 2,
    pattern = "LL",
    opcodes = "MOV,MOV,",
    offsets = "16,0,",
    addresses = "0xedd0,0xedfc,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 12,
    accessed_memory_nooverlap = 12,
    accessed_memory_overlap = 0,
    span = 20,
    head = 0,
    unroll_factor = 2,
  },
  {
    group_size = 4,
    pattern = "LLLL",
    opcodes = "MOV,MOV,MOV,MOV,",
    offsets = "24,24,24,24,",
    addresses = "0xede3,0xee1f,0xee56,0xee90,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 16,
    accessed_memory_nooverlap = 4,
    accessed_memory_overlap = 12,
    span = 4,
    head = 0,
    unroll_factor = 4,
  },
  {
    group_size = 2,
    pattern = "LL",
    opcodes = "MOV,MOV,",
    offsets = "16,0,",
    addresses = "0xee0c,0xee38,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 12,
    accessed_memory_nooverlap = 12,
    accessed_memory_overlap = 0,
    span = 20,
    head = 0,
    unroll_factor = 2,
  },
  {
    group_size = 4,
    pattern = "LLLL",
    opcodes = "MOV,MOV,MOV,MOV,",
    offsets = "16,16,16,16,",
    addresses = "0xedff,0xee3b,0xee74,0xeead,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 32,
    accessed_memory_nooverlap = 8,
    accessed_memory_overlap = 24,
    span = 8,
    head = 0,
    unroll_factor = 4,
  },
}
